package org.synthe.ridill.stub;

import org.synthe.ridill.stub.StubFactory.*;

import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;

import org.junit.Test;

import java.lang.reflect.Proxy;
import java.util.Collection;
public class StubFactoryTest {

	@Test
	public void type() throws Exception {
//		// TODO auto-generated by JUnit Helper.
//		assertThat(StubFactory.class, notNullValue());
	}

	@Test
	public void instantiation() throws Exception {
//		// TODO auto-generated by JUnit Helper.
//		StubFactory target = new StubFactory();
//		assertThat(target, notNullValue());
	}

	@Test
	public void create_A$Collection() throws Exception {
//		// TODO auto-generated by JUnit Helper.
//		StubFactory target = new StubFactory();
//		Collection<String> classNames = null;
//		Object actual = target.create(classNames);
//		Object expected = null;
//		assertThat(actual, is(equalTo(expected)));
	}

	@Test
	public void create_A$Collection_T$ClassNotFoundException() throws Exception {
//		// TODO auto-generated by JUnit Helper.
//		StubFactory target = new StubFactory();
//		Collection<String> classNames = null;
//		try {
//			target.create(classNames);
//			fail("Expected exception was not thrown!");
//		} catch (ClassNotFoundException e) {
//		}
	}

	@Test
	public void create_A$Object$Collection() throws Exception {
//		// TODO auto-generated by JUnit Helper.
//		StubFactory target = new StubFactory();
//		Object generator = null;
//		Collection<String> classNames = null;
//		Object actual = target.create(generator, classNames);
//		Object expected = null;
//		assertThat(actual, is(equalTo(expected)));
	}

	@Test
	public void create_A$ClassLoader$Collection() throws Exception {
//		// TODO auto-generated by JUnit Helper.
//		StubFactory target = new StubFactory();
//		ClassLoader loader = null;
//		Collection<String> classNames = null;
//		Object actual = target.create(loader, classNames);
//		Object expected = null;
//		assertThat(actual, is(equalTo(expected)));
	}

	@Test
	public void create_A$ClassLoader$Object$Collection() throws Exception {
//		// TODO auto-generated by JUnit Helper.
//		StubFactory target = new StubFactory();
//		ClassLoader loader = null;
//		Object generator = null;
//		Collection<String> classNames = null;
//		Object actual = target.create(loader, generator, classNames);
//		Object expected = null;
//		assertThat(actual, is(equalTo(expected)));
	}

	@Test
	public void create_A$ClassLoader$Object() throws Exception {
//		// TODO auto-generated by JUnit Helper.
//		StubFactory target = new StubFactory();
//		ClassLoader loader = null;
//		Object arg1 = null;
//		Object actual = target.create(loader, arg1);
//		Object expected = null;
//		assertThat(actual, is(equalTo(expected)));
	}

	@Test
	public void create_A$Object$Object() throws Exception {
//		// TODO auto-generated by JUnit Helper.
//		StubFactory target = new StubFactory();
//		Object generator = null;
//		Object arg1 = null;
//		Object actual = target.create(generator, arg1);
//		Object expected = null;
//		assertThat(actual, is(equalTo(expected)));
	}

	@Test
	public void create_A$Object() throws Exception {
//		// TODO auto-generated by JUnit Helper.
//		StubFactory target = new StubFactory();
//		Object arg0 = null;
//		Object actual = target.create(arg0);
//		Object expected = null;
//		assertThat(actual, is(equalTo(expected)));
	}

	@Test
	public void create_A$ClassLoader$Object$Object() throws Exception {
//		// TODO auto-generated by JUnit Helper.
//		StubFactory target = new StubFactory();
//		ClassLoader loader = null;
//		Object generator = null;
//		Object arg2 = null;
//		Object actual = target.create(loader, generator, arg2);
//		Object expected = null;
//		assertThat(actual, is(equalTo(expected)));
	}

}
