package org.synthe.ridill.scenario.domain;


public class TestGenericsTypeVariableUsePropertyTypeParameterNestImpl extends TestGenericsTypeVariableUsePropertyTypeParameterNest<TestEntity,TestEmbed>{
}
