package org.synthe.ridill.generator;

import org.synthe.ridill.generator.GeneratorAdapter.*;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;
import org.junit.Test;

import org.synthe.ridill.reflect.Adapter;
import org.synthe.ridill.reflect.ReflectionInfo;
public class GeneratorAdapterTest {

	@Test
	public void type() throws Exception {
//		// TODO auto-generated by JUnit Helper.
//		assertThat(GeneratorAdapter.class, notNullValue());
	}

	@Test
	public void instantiation() throws Exception {
//		// TODO auto-generated by JUnit Helper.
//		Object generator = null;
//		GeneratorAdapter target = new GeneratorAdapter(generator);
//		assertThat(target, notNullValue());
	}

	@Test
	public void getEmbedValue_A$ReflectionInfo$Object$Integer() throws Exception {
//		// TODO auto-generated by JUnit Helper.
//		Object generator = null;
//		GeneratorAdapter target = new GeneratorAdapter(generator);
//		ReflectionInfo info = null;
//		Object enclosingInstance = null;
//		Integer depth = null;
//		Object actual = target.getEmbedValue(info, enclosingInstance, depth);
//		Object expected = null;
//		assertThat(actual, is(equalTo(expected)));
	}

	@Test
	public void getObjectValue_A$ReflectionInfo$Object$Integer() throws Exception {
//		// TODO auto-generated by JUnit Helper.
//		Object generator = null;
//		GeneratorAdapter target = new GeneratorAdapter(generator);
//		ReflectionInfo info = null;
//		Object enclosingInstance = null;
//		Integer depth = null;
//		Object actual = target.getObjectValue(info, enclosingInstance, depth);
//		Object expected = null;
//		assertThat(actual, is(equalTo(expected)));
	}

	@Test
	public void getEnumValue_A$ReflectionInfo$Object$Integer() throws Exception {
//		// TODO auto-generated by JUnit Helper.
//		Object generator = null;
//		GeneratorAdapter target = new GeneratorAdapter(generator);
//		ReflectionInfo info = null;
//		Object enclosingInstance = null;
//		Integer depth = null;
//		Object actual = target.getEnumValue(info, enclosingInstance, depth);
//		Object expected = null;
//		assertThat(actual, is(equalTo(expected)));
	}

}
