package org.synthe.ridill.generator;

import org.synthe.ridill.generator.StubProxy.*;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;
import org.junit.Test;

import java.lang.reflect.InvocationHandler;
import java.lang.reflect.Method;
import org.synthe.ridill.reflect.ReflectService;
public class StubProxyTest {

	@Test
	public void type() throws Exception {
		// TODO auto-generated by JUnit Helper.
		assertThat(StubProxy.class, notNullValue());
	}

	@Test
	public void instantiation() throws Exception {
//		// TODO auto-generated by JUnit Helper.
//		ClassLoader loader = null;
//		Object generator = null;
//		StubProxy target = new StubProxy(loader, generator);
//		assertThat(target, notNullValue());
	}

	@Test
	public void invoke_A$Object$Method$ObjectArray() throws Throwable {
//		// TODO auto-generated by JUnit Helper.
//		ClassLoader loader = null;
//		Object generator = null;
//		StubProxy target = new StubProxy(loader, generator);
//		Object proxy = null;
//		Method method = null;
//		Object[] args = new Object[] {};
//		Object actual = target.invoke(proxy, method, args);
//		Object expected = null;
//		assertThat(actual, is(equalTo(expected)));
	}

	@Test
	public void invoke_A$Object$Method$ObjectArray_T$Throwable() throws Throwable {
//		// TODO auto-generated by JUnit Helper.
//		ClassLoader loader = null;
//		Object generator = null;
//		StubProxy target = new StubProxy(loader, generator);
//		Object proxy = null;
//		Method method = null;
//		Object[] args = new Object[] {};
//		try {
//			target.invoke(proxy, method, args);
//			fail("Expected exception was not thrown!");
//		} catch (Throwable e) {
//		}
	}

}
